# Generated by Django 5.2.16 on 2026-09-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningtrack',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
