# Generated by Django 5.2.16 on 2026-09-30 05:43

import apps.education.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_practicedefinition_lesson'),
        ('assessments', '0002_alter_test_lesson'),
        ('education', '0007_lesson_draft_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(default=apps.education.models.generate_short_id, editable=False, max_length=10, unique=True)),
                ('type', models.CharField(choices=[('LECTURE', 'Лекция'), ('TEST', 'Тест'), ('PRACTICE', 'Практика')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликован')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_item', to='education.lesson')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='education.module')),
                ('practice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_item', to='activities.practicedefinition')),
                ('test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_item', to='assessments.test')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('module', 'position'), name='unique_learning_item_position')],
            },
        ),
    ]
