# Generated by Django 5.2.16 on 2026-09-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image')], max_length=10)),
                ('position', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='education.lesson')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mediafiles.mediafile')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'position'), name='unique_block_position')],
            },
        ),
    ]
