# Generated by Django 5.2.16 on 2026-09-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practices', to='education.lesson')),
            ],
        ),
    ]
