# Generated by Django 5.2.16 on 2026-09-30 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('education', '0007_lesson_draft_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicedefinition',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practices', to='education.lesson'),
        ),
    ]
